# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, unique=True)),
                ('u_passwd', models.CharField(max_length=33)),
                ('u_icon', models.ImageField(upload_to='icons')),
                ('u_email', models.CharField(max_length=50)),
                ('u_phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
    ]
